# Generated by Django 4.1.5 on 2023-01-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('series', models.PositiveIntegerField()),
                ('numb', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(verbose_name='start activate date')),
                ('stop_date', models.DateTimeField(verbose_name='stop activate date')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('money', models.FloatField(default=0)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyaltycard.card')),
            ],
        ),
    ]
