# Generated by Django 4.1.5 on 2023-01-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltycard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='question_text',
        ),
    ]
